### ISSUE TITLE
Can't gunzip

### ISSUE THREAD

**Issue by nbctcp** [KaiLemke/cpt72-docker#1]
Your doc said, download PacketTracer as pt.tar.gz
So I download
PacketTracer-7.2.2-ubuntu-setup.run
and rename it as pt.tar.gz
# mv PacketTracer-7.2.2-ubuntu-setup.run pt.tar.gz
but I can't gunzip after that.
Do you think my steps is correct?
tq

**Comment by KaiLemke** [comment]
Have you tried `tar xzvf pt.tar.gz`?

Tar and zip are really not the same thing.

**Comment by nbctcp** [comment]
# cp PacketTracer-7.2.2-ubuntu-setup.run pt.tar.gz
# tar xzvf pt.tar.gz
tar: invalid magic
tar: short read

**Comment by KaiLemke** [comment]
Okay, you downloaded a run script, not a tar.gz. So Cisco has changed what they provide.
Have a look at PacketTracer-7.2.2-ubuntu-setup.run, inspect it with `file`, `less` and such and you will see what it does. Hopefully they've changed it in a way, that you don't need this docker workaround anymore.
